AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*
    - config/initializers/*

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
