AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*
    - config/initializers/*

Metrics/LineLength:
  Max: 100

Rails:
  Enabled: true

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
